server:
  port: 5005
spring:
  application:
    name: ramid-ua-platform-tms
  config:
    import:
      - optional:nacos:security.yaml
      - optional:nacos:cloud-default.yaml
      - optional:nacos:${spring.application.name}.properties
      - optional:nacos:mybatis-plus-default.yaml?group=DEFAULT_GROUP&refreshEnabled=true #这是完写法
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: ramid-ua
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: ramid-ua