server:
  port: 5002
spring:
  application:
    name: ramid-ua-platform-iam
  config:
    import:
      - optional:nacos:security.yaml
      - optional:nacos:cloud-default.yaml
      - optional:nacos:${spring.application.name}.properties
      - optional:nacos:mybatis-plus-default.yaml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: ramid-ua
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: ramid-ua
extend:
  third-auth:
    config-map:
      gitee:
        client-id:
        client-secret:
        redirect-uri: http://localhost:5002/third-auth/gitee/callback